name: Deploy to Salesforce Environments on Push to Main

on:
  push:
    branches: [ main ]
    paths:
      - 'force-app/**'

jobs:
  Deploy-to-Salesforce:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 2: Checkout source code
      - name: 'Checkout source code'
        uses: actions/checkout@v3
        with:
          fetch-depth: '2'

      # Step 3: Install Salesforce CLI
      - name: 'Install Salesforce CLI'
        run: npm install @salesforce/cli --global

      # Step 4: Authenticate to Dev1 and retrieve metadata
      - name: Authenticate to Dev1 and retrieve metadata
        run: |
          echo "${{ secrets.JWT_SERVER_KEY }}" > server.key
          sf org login jwt --username ${{ secrets.DEV1_USERNAME }} --jwt-key-file server.key --client-id ${{ secrets.DEV1_CLIENT_ID }} --instance-url https://test.salesforce.com --set-default
          sf project retrieve start --source-dir force-app --ignore-conflicts
          echo "[INFO] Metadata retrieved from Dev1"

      # Step 5: Create delta packages (detect changes dynamically)
      - name: 'Create delta packages'
        run: |
          mkdir -p changed-sources
          sf sgd source delta --to "HEAD" --from "HEAD~1" --output changed-sources/ --generate-delta --source force-app/
          ls -R changed-sources || echo "[INFO] No changes detected."

      # Step 6: Authenticate to Test1 and deploy metadata
      - name: Deploy Metadata to Test1
        run: |
          echo "${{ secrets.JWT_SERVER_KEY }}" > server.key
          sf org login jwt --username ${{ secrets.TEST1_USERNAME }} --jwt-key-file server.key --client-id ${{ secrets.TEST1_CLIENT_ID }} --instance-url https://test.salesforce.com --set-default
          if [ -d "changed-sources/force-app" ]; then
            sf project deploy start --source-dir changed-sources/force-app --test-level RunLocalTests --ignore-conflicts
          else
            echo "[INFO] No changes detected. Deploying entire force-app directory."
            sf project deploy start --source-dir force-app --test-level RunLocalTests --ignore-conflicts
          fi